import type { ImageKey } from "@/lib/images";

/**
 * The generator's raw material.
 *
 * These are real places, described in bands rather than fixed routes: a place
 * offers a *range* of distances, ascent and difficulty, and the engine picks a
 * point inside those bands. That is what lets the same valley produce a
 * two-hour evening loop and a full-day ridge traverse without repeating itself.
 *
 * Coordinates are approximate trailhead positions, accurate enough for travel
 * estimates and map links, and are not a substitute for a real route planner.
 */
export type LocationEntry = {
  id: string;
  /** The specific place a quest sends you to. */
  name: string;
  region: string;
  country: string;
  latitude: number;
  longitude: number;
  terrain: string[];
  features: string[];
  /** Named things on the ground — the raw material for bonus challenges. */
  landmarks: string[];
  /** [min, max] route length in km the area realistically supports. */
  distanceBand: [number, number];
  /** [min, max] ascent in metres. */
  elevationBand: [number, number];
  /** Difficulties this terrain can plausibly deliver. */
  difficulties: Array<"EASY" | "MODERATE" | "HARD" | "EXPERT">;
  /** How well the trailhead is served without a car. */
  transit: "good" | "ok" | "poor";
  imageKeys: ImageKey[];
  /** One clause, used verbatim inside generated descriptions. */
  character: string;
  /** Area-specific hazard note, appended to generic safety guidance. */
  caution?: string;
  /** Months (1–12) when the area is at its best. */
  bestMonths: number[];
};

export const LOCATIONS: LocationEntry[] = [
  {
    id: "janosikove-diery",
    name: "Jánošíkove diery",
    region: "Malá Fatra",
    country: "Slovakia",
    latitude: 49.2136,
    longitude: 19.0472,
    terrain: ["gorge", "forest", "rocks"],
    features: ["waterfall", "river", "hidden"],
    landmarks: ["the first chained ladder", "the confluence below Podžiar", "the wooden footbridge in Nové diery"],
    distanceBand: [5, 13],
    elevationBand: [280, 720],
    difficulties: ["MODERATE", "HARD"],
    transit: "good",
    imageKeys: ["waterfallForest", "rockyGorge", "riverValley"],
    character: "a chain of narrow gorges where the path climbs ladders directly beside the water",
    caution: "Ladders and chains get slick after rain, and the gorge is one-way in high season.",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "velky-rozsutec",
    name: "Veľký Rozsutec",
    region: "Malá Fatra",
    country: "Slovakia",
    latitude: 49.2036,
    longitude: 19.0839,
    terrain: ["mountains", "ridge", "rocks"],
    features: ["summit", "viewpoint", "sunset"],
    landmarks: ["the summit cross", "the last rock step before the top", "the saddle at Medziholie"],
    distanceBand: [9, 17],
    elevationBand: [700, 1250],
    difficulties: ["HARD", "EXPERT"],
    transit: "ok",
    imageKeys: ["summitFog", "sunsetRidge", "trailMarker"],
    character: "a blunt limestone cone that earns its view with a genuinely steep final section",
    caution: "The upper section is exposed; turn back in wind or storm forecasts.",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "sutovsky-vodopad",
    name: "Šútovský vodopád",
    region: "Malá Fatra",
    country: "Slovakia",
    latitude: 49.1372,
    longitude: 19.0447,
    terrain: ["forest", "valley", "rocks"],
    features: ["waterfall", "river", "hidden"],
    landmarks: ["the plunge pool at the base", "the old forestry road junction", "the boulder field below the fall"],
    distanceBand: [6, 14],
    elevationBand: [250, 780],
    difficulties: ["EASY", "MODERATE"],
    transit: "ok",
    imageKeys: ["waterfallForest", "forestPath", "riverValley"],
    character: "one of the highest waterfalls in the country, hidden at the end of a quiet forest valley",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "sulovske-skaly",
    name: "Súľovské skaly",
    region: "Súľovské vrchy",
    country: "Slovakia",
    latitude: 49.1611,
    longitude: 18.5947,
    terrain: ["rocks", "forest", "gorge"],
    features: ["ruins", "viewpoint", "hidden"],
    landmarks: ["the Gothic gate arch", "the ruins of Súľov castle", "the rock window above the village"],
    distanceBand: [6, 12],
    elevationBand: [300, 620],
    difficulties: ["EASY", "MODERATE"],
    transit: "ok",
    imageKeys: ["rockyGorge", "ruins", "forestPath"],
    character: "conglomerate towers, a natural rock gate and a ruined castle stacked into one short loop",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "vratna-chleb",
    name: "Chleb and the Vrátna ridge",
    region: "Malá Fatra",
    country: "Slovakia",
    latitude: 49.1786,
    longitude: 19.0261,
    terrain: ["ridge", "mountains", "meadow"],
    features: ["summit", "viewpoint", "sunrise"],
    landmarks: ["the ridge junction sign at Snilovské sedlo", "the wind-bent pines below Chleb"],
    distanceBand: [8, 19],
    elevationBand: [500, 1100],
    difficulties: ["MODERATE", "HARD"],
    transit: "good",
    imageKeys: ["summitFog", "trailMarker", "winterRidge"],
    character: "an open grassy ridge where you can see the whole range at once",
    caution: "The ridge is fully exposed to weather — no shelter between saddles.",
    bestMonths: [6, 7, 8, 9, 10],
  },
  {
    id: "gaderska-dolina",
    name: "Gaderská dolina",
    region: "Veľká Fatra",
    country: "Slovakia",
    latitude: 48.9008,
    longitude: 18.9283,
    terrain: ["valley", "forest", "rocks"],
    features: ["river", "old_growth", "hidden"],
    landmarks: ["the limestone narrows", "the meadow clearing at Dedošova", "the old charcoal pit"],
    distanceBand: [7, 18],
    elevationBand: [200, 700],
    difficulties: ["EASY", "MODERATE"],
    transit: "poor",
    imageKeys: ["forestPath", "riverValley", "meadowMorning"],
    character: "a long limestone valley that stays cool and green even in August",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "ostra-tlsta",
    name: "Ostrá and Tlstá",
    region: "Veľká Fatra",
    country: "Slovakia",
    latitude: 48.9528,
    longitude: 19.0122,
    terrain: ["rocks", "ridge", "forest"],
    features: ["summit", "viewpoint", "cave"],
    landmarks: ["the Mažarná cave entrance", "the twin summit saddle"],
    distanceBand: [9, 16],
    elevationBand: [650, 1000],
    difficulties: ["MODERATE", "HARD"],
    transit: "poor",
    imageKeys: ["cave", "summitFog", "forestPath"],
    character: "two rock summits over a cave-riddled hillside, steep from the first step",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "dumbier",
    name: "Ďumbier",
    region: "Nízke Tatry",
    country: "Slovakia",
    latitude: 48.9403,
    longitude: 19.6486,
    terrain: ["mountains", "ridge", "rocks"],
    features: ["summit", "viewpoint", "sunrise"],
    landmarks: ["the summit plaque", "the scree traverse under the ridge", "the mountain hut below the saddle"],
    distanceBand: [12, 24],
    elevationBand: [900, 1500],
    difficulties: ["HARD", "EXPERT"],
    transit: "ok",
    imageKeys: ["winterRidge", "summitFog", "trailMarker"],
    character: "the high point of the range, a long approach and a genuinely alpine finish",
    caution: "Above 1,700 m the weather turns fast. Start early and carry layers.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    id: "demanovska-dolina",
    name: "Demänovská dolina",
    region: "Nízke Tatry",
    country: "Slovakia",
    latitude: 48.9861,
    longitude: 19.5822,
    terrain: ["valley", "karst", "forest"],
    features: ["cave", "river", "hidden"],
    landmarks: ["the cave entrance terrace", "the sinkhole above the path", "the resurgence spring"],
    distanceBand: [5, 14],
    elevationBand: [200, 650],
    difficulties: ["EASY", "MODERATE"],
    transit: "good",
    imageKeys: ["cave", "forestPath", "riverValley"],
    character: "a karst valley where the river disappears underground and comes back somewhere else",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "mlynicka-skok",
    name: "Mlynická dolina and the Skok waterfall",
    region: "Vysoké Tatry",
    country: "Slovakia",
    latitude: 49.1414,
    longitude: 20.0561,
    terrain: ["valley", "mountains", "rocks"],
    features: ["waterfall", "lake", "summit"],
    landmarks: ["the chain beside the falls", "Pleso nad Skokom", "the first tarn above the treeline"],
    distanceBand: [10, 20],
    elevationBand: [600, 1300],
    difficulties: ["MODERATE", "HARD"],
    transit: "good",
    imageKeys: ["waterfallForest", "alpineLake", "summitFog"],
    character: "a hanging valley stacked with tarns above a waterfall you climb straight past",
    caution: "High Tatras trails close in winter. Check the seasonal closure dates.",
    bestMonths: [6, 7, 8, 9, 10],
  },
  {
    id: "velke-hincovo",
    name: "Veľké Hincovo pleso",
    region: "Vysoké Tatry",
    country: "Slovakia",
    latitude: 49.1747,
    longitude: 20.0567,
    terrain: ["mountains", "rocks", "valley"],
    features: ["lake", "viewpoint", "summit"],
    landmarks: ["the boulder shore on the far side", "the last switchback before the lake"],
    distanceBand: [13, 22],
    elevationBand: [700, 1200],
    difficulties: ["MODERATE", "HARD"],
    transit: "good",
    imageKeys: ["alpineLake", "lakeReflection", "winterRidge"],
    character: "the deepest lake in the range, sitting in a bowl of grey granite",
    caution: "Long day. The last bus down leaves earlier than you think.",
    bestMonths: [6, 7, 8, 9, 10],
  },
  {
    id: "zdiar-meadows",
    name: "Ždiar and the Belianske meadows",
    region: "Belianske Tatry",
    country: "Slovakia",
    latitude: 49.2703,
    longitude: 20.2669,
    terrain: ["meadow", "forest", "mountains"],
    features: ["viewpoint", "wildlife", "sunset"],
    landmarks: ["the painted wooden houses on the old road", "the meadow chapel", "the fence line above the village"],
    distanceBand: [6, 15],
    elevationBand: [250, 700],
    difficulties: ["EASY", "MODERATE"],
    transit: "good",
    imageKeys: ["meadowMorning", "sunsetRidge", "forestPath"],
    character: "open hay meadows with the whole Belianske wall standing behind them",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "sucha-bela",
    name: "Suchá Belá",
    region: "Slovenský raj",
    country: "Slovakia",
    latitude: 48.9436,
    longitude: 20.3706,
    terrain: ["gorge", "forest", "rocks"],
    features: ["waterfall", "river", "hidden"],
    landmarks: ["the Misové falls ladder", "the ravine exit onto the plateau", "the wooden bridge at the entrance"],
    distanceBand: [7, 14],
    elevationBand: [350, 700],
    difficulties: ["MODERATE", "HARD"],
    transit: "ok",
    imageKeys: ["waterfallForest", "rockyGorge", "forestPath"],
    character: "a one-way ravine climbed on ladders bolted beside the waterfalls",
    caution: "One-way traffic only. Do not descend the ladders.",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "klastorisko",
    name: "Kláštorisko",
    region: "Slovenský raj",
    country: "Slovakia",
    latitude: 48.9219,
    longitude: 20.3928,
    terrain: ["plateau", "forest", "karst"],
    features: ["ruins", "viewpoint", "hidden"],
    landmarks: ["the excavated monastery walls", "the Tomášovský výhľad overhang"],
    distanceBand: [8, 16],
    elevationBand: [300, 650],
    difficulties: ["EASY", "MODERATE"],
    transit: "ok",
    imageKeys: ["ruins", "forestPath", "rockyGorge"],
    character: "a ruined Carthusian monastery on a plateau you can only reach on foot",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "zadielska-tiesnava",
    name: "Zádielska tiesňava",
    region: "Slovenský kras",
    country: "Slovakia",
    latitude: 48.6183,
    longitude: 20.8461,
    terrain: ["gorge", "karst", "rocks"],
    features: ["viewpoint", "hidden", "river"],
    landmarks: ["the Cukrová homoľa pinnacle", "the plateau rim above the gorge"],
    distanceBand: [6, 13],
    elevationBand: [300, 600],
    difficulties: ["EASY", "MODERATE"],
    transit: "ok",
    imageKeys: ["rockyGorge", "meadowMorning", "forestPath"],
    character: "a 400-metre-deep limestone slot that opens onto an empty karst plateau",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "muranska-planina",
    name: "Muránska planina",
    region: "Muránska planina",
    country: "Slovakia",
    latitude: 48.7511,
    longitude: 20.0578,
    terrain: ["plateau", "forest", "karst"],
    features: ["ruins", "wildlife", "hidden"],
    landmarks: ["the castle ruin on the cliff edge", "the wild horse pasture", "the spring below the plateau"],
    distanceBand: [9, 20],
    elevationBand: [400, 850],
    difficulties: ["MODERATE", "HARD"],
    transit: "poor",
    imageKeys: ["ruins", "meadowMorning", "forestPath"],
    character: "an empty karst plateau with a cliff-top castle ruin and semi-wild horses",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "morske-oko",
    name: "Morské oko",
    region: "Vihorlat",
    country: "Slovakia",
    latitude: 48.9078,
    longitude: 22.2158,
    terrain: ["forest", "mountains", "valley"],
    features: ["lake", "old_growth", "viewpoint"],
    landmarks: ["the dam wall at the outflow", "the Sninský kameň rock stack"],
    distanceBand: [7, 17],
    elevationBand: [250, 750],
    difficulties: ["EASY", "MODERATE"],
    transit: "poor",
    imageKeys: ["lakeReflection", "forestPath", "alpineLake"],
    character: "a volcanic lake ringed by beech forest that turns copper in October",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "sninsky-kamen",
    name: "Sninský kameň",
    region: "Vihorlat",
    country: "Slovakia",
    latitude: 48.9375,
    longitude: 22.2794,
    terrain: ["rocks", "forest"],
    features: ["viewpoint", "summit", "sunset"],
    landmarks: ["the metal stairway to the upper platform", "the twin rock summits"],
    distanceBand: [6, 13],
    elevationBand: [350, 700],
    difficulties: ["MODERATE"],
    transit: "poor",
    imageKeys: ["summitFog", "sunsetRidge", "forestPath"],
    character: "two andesite blocks standing clear above the forest, reached by an iron stairway",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "kremenec",
    name: "Kremenec",
    region: "Poloniny",
    country: "Slovakia",
    latitude: 49.0847,
    longitude: 22.5486,
    terrain: ["ridge", "forest", "meadow"],
    features: ["viewpoint", "wildlife", "old_growth"],
    landmarks: ["the tripoint marker where three countries meet", "the open polonina grassland"],
    distanceBand: [11, 21],
    elevationBand: [500, 900],
    difficulties: ["MODERATE", "HARD"],
    transit: "poor",
    imageKeys: ["meadowMorning", "trailMarker", "forestPath"],
    character: "the emptiest corner of the country, where three borders meet on an open grass ridge",
    caution: "No phone signal for long stretches. Tell someone your plan.",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "vapec",
    name: "Vápeč",
    region: "Strážovské vrchy",
    country: "Slovakia",
    latitude: 48.9425,
    longitude: 18.4189,
    terrain: ["rocks", "forest", "meadow"],
    features: ["summit", "viewpoint", "sunset"],
    landmarks: ["the summit cross", "the old quarry track"],
    distanceBand: [5, 11],
    elevationBand: [400, 700],
    difficulties: ["MODERATE"],
    transit: "ok",
    imageKeys: ["sunsetRidge", "summitFog", "meadowMorning"],
    character: "a sharp limestone cap that gives you the whole Považie valley in one turn",
    bestMonths: [3, 4, 5, 6, 7, 8, 9, 10, 11],
  },
  {
    id: "velka-javorina",
    name: "Veľká Javorina",
    region: "Biele Karpaty",
    country: "Slovakia",
    latitude: 48.8583,
    longitude: 17.6767,
    terrain: ["meadow", "forest", "ridge"],
    features: ["viewpoint", "wildlife", "sunrise"],
    landmarks: ["the border stone on the ridge", "the meadow spring"],
    distanceBand: [8, 18],
    elevationBand: [350, 750],
    difficulties: ["EASY", "MODERATE"],
    transit: "poor",
    imageKeys: ["meadowMorning", "forestPath", "trailMarker"],
    character: "rolling border meadows where the trail runs with one foot in each country",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "cachticky-hrad",
    name: "Čachtický hrad",
    region: "Malé Karpaty",
    country: "Slovakia",
    latitude: 48.7239,
    longitude: 17.7625,
    terrain: ["forest", "meadow", "rocks"],
    features: ["castle", "ruins", "viewpoint"],
    landmarks: ["the outer curtain wall", "the karst meadow below the ridge"],
    distanceBand: [5, 12],
    elevationBand: [250, 520],
    difficulties: ["EASY", "MODERATE"],
    transit: "ok",
    imageKeys: ["ruins", "meadowMorning", "forestPath"],
    character: "a ruin with a bad reputation on a dry limestone ridge above the vineyards",
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
  },
  {
    id: "devinska-kobyla",
    name: "Devínska Kobyla",
    region: "Malé Karpaty",
    country: "Slovakia",
    latitude: 48.1836,
    longitude: 16.9861,
    terrain: ["forest", "meadow", "rocks"],
    features: ["viewpoint", "ruins", "sunset"],
    landmarks: ["the Sandberg fossil cliff", "the castle rock above the river confluence"],
    distanceBand: [5, 13],
    elevationBand: [180, 450],
    difficulties: ["EASY"],
    transit: "good",
    imageKeys: ["sunsetRidge", "forestPath", "meadowMorning"],
    character: "a fossil cliff and a river confluence, twenty minutes from a capital city",
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
  },
  {
    id: "tematin",
    name: "Tematínsky hrad",
    region: "Považský Inovec",
    country: "Slovakia",
    latitude: 48.6839,
    longitude: 17.9231,
    terrain: ["forest", "rocks", "ridge"],
    features: ["castle", "ruins", "hidden"],
    landmarks: ["the restored gate tower", "the cistern in the lower courtyard"],
    distanceBand: [7, 15],
    elevationBand: [350, 700],
    difficulties: ["MODERATE"],
    transit: "poor",
    imageKeys: ["ruins", "forestPath", "summitFog"],
    character: "a ruin deep enough in the forest that you hear it before you see it",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "sitno",
    name: "Sitno",
    region: "Štiavnické vrchy",
    country: "Slovakia",
    latitude: 48.4028,
    longitude: 18.8697,
    terrain: ["forest", "rocks", "mountains"],
    features: ["summit", "ruins", "viewpoint"],
    landmarks: ["the lookout tower on the summit", "the castle remains below the plateau", "the lake at Počúvadlo"],
    distanceBand: [6, 14],
    elevationBand: [350, 650],
    difficulties: ["EASY", "MODERATE"],
    transit: "ok",
    imageKeys: ["summitFog", "ruins", "lakeReflection"],
    character: "an old volcano with a castle, a tower and a lake at the bottom of the hill",
    bestMonths: [4, 5, 6, 7, 8, 9, 10, 11],
  },
  {
    id: "polana",
    name: "Poľana",
    region: "Poľana",
    country: "Slovakia",
    latitude: 48.6386,
    longitude: 19.5008,
    terrain: ["mountains", "forest", "meadow"],
    features: ["summit", "wildlife", "old_growth"],
    landmarks: ["the caldera rim", "the shepherd's hut clearing", "the spring under the summit"],
    distanceBand: [10, 20],
    elevationBand: [600, 1000],
    difficulties: ["MODERATE", "HARD"],
    transit: "poor",
    imageKeys: ["forestPath", "meadowMorning", "summitFog"],
    character: "the rim of Europe's largest extinct volcano, mostly forest and mostly empty",
    caution: "Active bear country. Make noise on blind corners.",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "simonka",
    name: "Šimonka",
    region: "Slanské vrchy",
    country: "Slovakia",
    latitude: 48.8331,
    longitude: 21.4194,
    terrain: ["forest", "rocks", "ridge"],
    features: ["summit", "viewpoint", "hidden"],
    landmarks: ["the andesite boulder field", "the ridge junction post"],
    distanceBand: [8, 16],
    elevationBand: [400, 800],
    difficulties: ["MODERATE"],
    transit: "poor",
    imageKeys: ["forestPath", "summitFog", "autumnForest"],
    character: "the high point of a forgotten volcanic range, all beech forest and loose stone",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "spissky-hrad",
    name: "Spišský hrad and Dreveník",
    region: "Spiš",
    country: "Slovakia",
    latitude: 48.9997,
    longitude: 20.7681,
    terrain: ["meadow", "karst", "rocks"],
    features: ["castle", "ruins", "viewpoint"],
    landmarks: ["the travertine blocks of Dreveník", "the castle's upper courtyard", "the chapter town gate"],
    distanceBand: [6, 14],
    elevationBand: [200, 480],
    difficulties: ["EASY", "MODERATE"],
    transit: "ok",
    imageKeys: ["ruins", "meadowMorning", "sunsetRidge"],
    character: "the largest castle complex in Central Europe, approached across open travertine meadows",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "tri-koruny",
    name: "Tri koruny and the Dunajec",
    region: "Pieniny",
    country: "Slovakia",
    latitude: 49.4131,
    longitude: 20.4108,
    terrain: ["rocks", "forest", "valley"],
    features: ["viewpoint", "river", "summit"],
    landmarks: ["the viewing platform over the gorge", "the river bend at Červený Kláštor"],
    distanceBand: [8, 17],
    elevationBand: [400, 800],
    difficulties: ["MODERATE"],
    transit: "ok",
    imageKeys: ["riverValley", "summitFog", "rockyGorge"],
    character: "a limestone crown standing over a river gorge that marks a border",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "rohace",
    name: "Roháčske plesá",
    region: "Západné Tatry",
    country: "Slovakia",
    latitude: 49.1958,
    longitude: 19.7433,
    terrain: ["mountains", "valley", "rocks"],
    features: ["lake", "waterfall", "summit"],
    landmarks: ["the chain of four tarns", "the waterfall below the first lake", "the hut at the valley head"],
    distanceBand: [11, 21],
    elevationBand: [600, 1200],
    difficulties: ["MODERATE", "HARD"],
    transit: "ok",
    imageKeys: ["alpineLake", "waterfallForest", "winterRidge"],
    character: "four glacial tarns strung up a valley below a serrated ridge",
    caution: "Snow lingers in the upper valley into June.",
    bestMonths: [6, 7, 8, 9, 10],
  },
  {
    id: "kvacianska-dolina",
    name: "Kvačianska dolina",
    region: "Orava",
    country: "Slovakia",
    latitude: 49.1583,
    longitude: 19.5528,
    terrain: ["gorge", "valley", "forest"],
    features: ["river", "hidden", "old_growth"],
    landmarks: ["the restored water mill", "the wooden flume above the stream", "the narrows where the path is cut into rock"],
    distanceBand: [6, 13],
    elevationBand: [250, 600],
    difficulties: ["EASY", "MODERATE"],
    transit: "poor",
    imageKeys: ["riverValley", "forestPath", "waterfallForest"],
    character: "a working water mill at the bottom of a gorge nobody drives past by accident",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: "velky-choc",
    name: "Veľký Choč",
    region: "Chočské vrchy",
    country: "Slovakia",
    latitude: 49.1394,
    longitude: 19.3803,
    terrain: ["mountains", "rocks", "meadow"],
    features: ["summit", "viewpoint", "sunrise"],
    landmarks: ["the summit panorama board", "the scree traverse on the north side"],
    distanceBand: [8, 15],
    elevationBand: [700, 1100],
    difficulties: ["MODERATE", "HARD"],
    transit: "poor",
    imageKeys: ["summitFog", "sunsetRidge", "winterRidge"],
    character: "a standalone limestone peak that sees both the Tatras and the Fatras on a clear day",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "zobor",
    name: "Zobor and Pyramída",
    region: "Tribeč",
    country: "Slovakia",
    latitude: 48.3436,
    longitude: 18.1006,
    terrain: ["forest", "rocks", "meadow"],
    features: ["viewpoint", "ruins", "sunset"],
    landmarks: ["the transmitter on the summit", "the abandoned quarry face", "the hermitage ruins"],
    distanceBand: [6, 14],
    elevationBand: [300, 650],
    difficulties: ["EASY", "MODERATE"],
    transit: "good",
    imageKeys: ["sunsetRidge", "forestPath", "meadowMorning"],
    character: "a city-edge ridge of dry oak forest that turns gold an hour before sunset",
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
  },
  {
    id: "somoska",
    name: "Šomoška",
    region: "Cerová vrchovina",
    country: "Slovakia",
    latitude: 48.2011,
    longitude: 19.8489,
    terrain: ["rocks", "forest"],
    features: ["castle", "ruins", "hidden"],
    landmarks: ["the stone waterfall of basalt columns", "the restored castle tower"],
    distanceBand: [5, 11],
    elevationBand: [200, 450],
    difficulties: ["EASY"],
    transit: "poor",
    imageKeys: ["ruins", "rockyGorge", "forestPath"],
    character: "a castle on a basalt plug, with a frozen 'stone waterfall' of hexagonal columns below it",
    bestMonths: [3, 4, 5, 6, 7, 8, 9, 10, 11],
  },
  {
    id: "havrania-skala",
    name: "Havrania skala",
    region: "Slovenský raj",
    country: "Slovakia",
    latitude: 48.8642,
    longitude: 20.3897,
    terrain: ["rocks", "forest", "plateau"],
    features: ["viewpoint", "hidden", "sunrise"],
    landmarks: ["the cliff edge above the reservoir", "the ice cave entrance below the path"],
    distanceBand: [7, 15],
    elevationBand: [350, 700],
    difficulties: ["MODERATE"],
    transit: "ok",
    imageKeys: ["summitFog", "forestPath", "rockyGorge"],
    character: "a cliff edge over a reservoir, with an ice cave hidden underneath the approach",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "velka-raca",
    name: "Veľká Rača",
    region: "Kysuce",
    country: "Slovakia",
    latitude: 49.3958,
    longitude: 18.9994,
    terrain: ["ridge", "forest", "meadow"],
    features: ["viewpoint", "summit", "sunset"],
    landmarks: ["the tripoint ridge marker", "the meadow below the summit"],
    distanceBand: [9, 18],
    elevationBand: [450, 900],
    difficulties: ["MODERATE"],
    transit: "ok",
    imageKeys: ["meadowMorning", "sunsetRidge", "trailMarker"],
    character: "a broad border ridge where the forest opens into long grass runs",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "velky-javornik",
    name: "Veľký Javorník",
    region: "Javorníky",
    country: "Slovakia",
    latitude: 49.3197,
    longitude: 18.3597,
    terrain: ["ridge", "meadow", "forest"],
    features: ["viewpoint", "sunrise", "wildlife"],
    landmarks: ["the summit shelter", "the fence line along the ridge"],
    distanceBand: [7, 16],
    elevationBand: [350, 750],
    difficulties: ["EASY", "MODERATE"],
    transit: "poor",
    imageKeys: ["meadowMorning", "trailMarker", "sunsetRidge"],
    character: "long open pasture ridges that feel much higher than they are",
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
  },
];
